version: '3.8'

services:
  db:
    build: ./db
    container_name: mongodb
    ports:
      - "5000:5000"
    volumes:
      - mongo_data:/data/db

  restserver:
    build: ./restserver
    container_name: restserver
    environment:
      - MONGO_URI=mongodb://db:5000
    ports:
      - "5000:5000"
    depends_on:
      - db

  restclient:
    build: ./restclient
    container_name: restclient
    depends_on:
      - restserver

volumes:
  mongo_data:
