# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cprotos.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12,\n\x08\x64\x61tetime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06system\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x05\"#\n\x0fMessageResponse\x12\x10\n\x08response\x18\x01 \x01(\t2O\n\x12SendMessageService\x12\x39\n\x0bSendMessage\x12\x0f.protos.Message\x1a\x17.protos.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=57
  _globals['_MESSAGE']._serialized_end=158
  _globals['_MESSAGERESPONSE']._serialized_start=160
  _globals['_MESSAGERESPONSE']._serialized_end=195
  _globals['_SENDMESSAGESERVICE']._serialized_start=197
  _globals['_SENDMESSAGESERVICE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
